import sharp from 'sharp'
import { contentHash, type ResolvedRep } from '@cairn/protocol'
import { PRIMARY_REP_ORDER } from './classify-kind'

/** Metadata riders and hint markers. Never content, never hashed, never stored. */
export const DROPPED_UTIS: readonly string[] = [
  'org.chromium.source-url', 'org.chromium.web-custom-data', 'org.nspasteboard.source',
  'org.nspasteboard.ConcealedType', 'org.nspasteboard.TransientType', 'org.nspasteboard.AutoGeneratedType',
  'com.apple.pasteboard.promised-file-content-type',
]

/** `pb.types` leaks these old NeXT/AppKit aliases beside the modern UTI for the same bytes. */
export const LEGACY_UTI_ALIASES: Readonly<Record<string, string>> = {
  NSStringPboardType: 'public.utf8-plain-text',
  NSPasteboardTypeString: 'public.utf8-plain-text',
  'NeXT plain ascii pasteboard type': 'public.utf8-plain-text',
  NSHTMLPboardType: 'public.html',
  NSPasteboardTypeHTML: 'public.html',
  NSRTFPboardType: 'public.rtf',
  'NeXT Rich Text Format pasteboard type': 'public.rtf',
  NSFilenamesPboardType: 'public.file-url',
  NSTIFFPboardType: 'public.tiff',
  NSPasteboardTypeTIFF: 'public.tiff',
  NSURLPboardType: 'public.url',
}

const CF_HTML_HEADER_RE = /^Version:\s*\d+\.\d+/

function reseal(rep: ResolvedRep, bytes: Uint8Array, mime = rep.mime, uti = rep.uti): ResolvedRep {
  return { mime, uti, bytes, byteLength: bytes.length, sha256: contentHash(bytes) }
}

/**
 * Windows `HTML Format` wraps the markup in a byte-offset header. Returns the bare fragment, or
 * `null` when the input is already bare HTML. Offsets are read leniently: prefer
 * StartFragment/EndFragment, fall back to StartHTML/EndHTML, then to the first `<`.
 */
export function stripCfHtml(bytes: Uint8Array): Uint8Array | null {
  const buf = Buffer.from(bytes)
  const text = buf.toString('utf8')
  if (!CF_HTML_HEADER_RE.test(text)) return null
  const num = (name: string): number => {
    const m = new RegExp(`^${name}:\\s*(\\d+)\\s*$`, 'm').exec(text)
    return m?.[1] === undefined ? -1 : Number(m[1])
  }
  const usable = (s: number, e: number): boolean => s >= 0 && e > s && e <= buf.length
  let start = num('StartFragment')
  let end = num('EndFragment')
  if (!usable(start, end)) { start = num('StartHTML'); end = num('EndHTML') }
  if (!usable(start, end)) {
    const lt = buf.indexOf(0x3c)
    if (lt < 0) return null
    start = lt
    end = buf.length
  }
  const inner = buf.subarray(start, end).toString('utf8').replace(/<!--\s*(?:Start|End)Fragment\s*-->/g, '')
  return Buffer.from(inner.trim(), 'utf8')
}

/** RFC 2483 canonical form: LF endings, no comments, no blanks, one trailing LF, no localhost. */
export function canonicaliseUriList(bytes: Uint8Array): Uint8Array {
  const out: string[] = []
  for (const rawLine of Buffer.from(bytes).toString('utf8').split('\n')) {
    const line = rawLine.replace(/\r$/, '').trim()
    if (line === '' || line.startsWith('#')) continue
    out.push(line.replace(/^file:\/\/localhost\//i, 'file:///'))
  }
  return Buffer.from(out.length === 0 ? '' : `${out.join('\n')}\n`, 'utf8')
}

/**
 * One rep per mime, canonical bytes, resealed hashes, deterministic order. Never writes a file:
 * sharp is Buffer-in/Buffer-out. An unreadable image is dropped, never spooled.
 */
export async function normalizeReps(raw: readonly ResolvedRep[]): Promise<readonly ResolvedRep[]> {
  const staged: ResolvedRep[] = []
  for (const rep of raw) {
    if (rep.uti !== null && DROPPED_UTIS.includes(rep.uti)) continue
    const uti = rep.uti !== null ? (LEGACY_UTI_ALIASES[rep.uti] ?? rep.uti) : null
    if (rep.mime === 'image/tiff') {
      try {
        const png = await sharp(Buffer.from(rep.bytes)).png({ compressionLevel: 9 }).toBuffer()
        staged.push(reseal(rep, png, 'image/png', 'public.png'))
      } catch { /* an unreadable image is dropped; the other reps still make a candidate */ }
      continue
    }
    if (rep.mime === 'text/html') {
      const stripped = stripCfHtml(rep.bytes)
      staged.push(stripped === null ? reseal(rep, rep.bytes, rep.mime, uti) : reseal(rep, stripped, 'text/html', uti))
      continue
    }
    if (rep.mime === 'text/uri-list') {
      staged.push(reseal(rep, canonicaliseUriList(rep.bytes), rep.mime, uti))
      continue
    }
    staged.push(reseal(rep, rep.bytes, rep.mime, uti))     // text/plain passes through byte-exact
  }
  const byMime = new Map<string, ResolvedRep>()
  for (const rep of staged) if (!byMime.has(rep.mime)) byMime.set(rep.mime, rep)
  const rank = (mime: string): number => {
    const i = PRIMARY_REP_ORDER.indexOf(mime)
    return i < 0 ? PRIMARY_REP_ORDER.length : i
  }
  return [...byMime.values()].sort((a, b) => rank(a.mime) - rank(b.mime) || a.mime.localeCompare(b.mime))
}
