// packages/protocol/src/constants.ts — the ONE place names and limits live.

export const WIRE_MAJOR = 1 as const

/** Product identity. */
export const APP_NAME = 'Cairn'
export const BUNDLE_ID = 'app.cairn.desktop'
export const APP_DESKTOP_NAME = 'app.cairn.desktop'     // app.setDesktopName(), Linux/M4
export const MDNS_SERVICE_TYPE = '_cairn._tcp'          // M5–M6 only; no socket in M1
export const SYNC_PORT = 47811                          // M6 only; nothing binds it in M1
export const NPM_SCOPE = '@cairn'
export const DATA_DIR_NAME = 'Cairn'                    // app.setName() -> userData basename
export const STORE_LOG_FILE = 'history.ndjson'
export const STORE_META_FILE = 'meta.json'
export const STORE_KEY_FILE = 'key.bin'
export const STORE_BLOB_DIR = 'blobs'
export const AGENT_BIN_NAME = 'cairn-agent-macos'

/** Crypto domain separation strings. Changing one is a store format break. */
export const STORE_AAD_MAGIC = 'cairn/store/v1'
export const BLOB_HKDF_INFO = 'cairn/blob/v1'

/** Byte transport (§4). */
export const CHUNK_THRESHOLD_BYTES = 65_536
export const CHUNK_PAYLOAD_BYTES = 32_768
export const MAX_REP_BYTES = 20_971_520
export const MAX_LINE_BYTES = 1_048_576
export const REP_STREAM_TIMEOUT_MS = 5_000
export const MAX_CONCURRENT_REP_STREAMS = 8

/** Behaviour (§5.7). */
export const DEFAULT_ACCELERATOR = 'Cmd+Shift+V'
export const WATCH_INTERVAL_MS = 500
export const CAPTURE_DEBOUNCE_MS = 150
export const AGENT_REQUEST_TIMEOUT_MS = 2_000
export const SECRET_TTL_MS = 300_000
export const RETENTION_MAX_ITEMS = 500
export const RETENTION_MAX_AGE_MS = 30 * 24 * 60 * 60 * 1_000
export const RETENTION_MAX_BYTES = 512 * 1024 * 1024
export const SEARCH_INDEX_DEFAULT = 500
export const SEARCH_INDEX_HARD_CAP = 2_000
export const PREVIEW_MAX_CHARS = 512
export const THUMBNAIL_MAX_EDGE_PX = 256
export const THUMBNAIL_JPEG_QUALITY = 70
export const THUMBNAIL_MAX_BYTES = 24 * 1024
export const SCRYPT_PARAMS = { N: 2 ** 17, r: 8, p: 1, maxmem: 192 * 1024 * 1024 } as const

/** The mime the macOS agent emits for Chrome's `org.chromium.source-url` rider. Frozen here so the
 *  agent and the capture layer cannot disagree; it is NOT `text/uri-list` and must never classify
 *  as a file list. */
export const MIME_SOURCE_URL = 'text/x-source-url'

/** The frozen mask format (contract §5.7, spec §11 control 5). `packages/privacy/src/mask.ts`
 *  imports these two — there is exactly one implementation of the format in the repo. */
export const MASK_BULLET = '•'
/** `AKIA••••A7QD`: first 4 + four bullets + last 4. Under 12 chars, eight bullets and nothing else,
 *  so a short secret leaks not even its length. */
export function maskToken(raw: string): string {
  return raw.length >= 12 ? raw.slice(0, 4) + MASK_BULLET.repeat(4) + raw.slice(-4) : MASK_BULLET.repeat(8)
}

/** User-visible strings held as constants so they cannot silently drift (spec §11 control 11). */
export const TOAST_COPIED_MANUAL = 'Copied — press Cmd+V'
export const TOAST_COPIED_SECURE_INPUT = 'A password field is focused — press Cmd+V yourself'
export const BANNER_KEYRING_WEAK =
  'Your desktop has no secure keyring, so Cairn will not pretend to encrypt. Set a passphrase.'

/** The canary used by the security suite. */
export const TEST_CANARY = 'CAIRN-CANARY-9f3a1c7e'

/** macOS pasteboard hint UTIs, probed BEFORE any byte is read. */
export const UTI_CONCEALED = 'org.nspasteboard.ConcealedType'
export const UTI_TRANSIENT = 'org.nspasteboard.TransientType'
export const UTI_AUTO_GENERATED = 'org.nspasteboard.AutoGeneratedType'
