import type { AgentCapabilities, AgentMethod, AgentParams, AgentResult } from './agent'
import type { LogLevel } from './log'
import type { ErrorCode, Result } from './result'

// -------------------------------------------------------------- branded primitives

declare const contentHashBrand: unique symbol
/** Always the string `sha256-` followed by 43 chars of unpadded base64url. */
export type ContentHash = string & { readonly [contentHashBrand]: 'sha256-b64url' }
export type BlobId = ContentHash

declare const itemIdBrand: unique symbol
/** 26-char Crockford base32: 10 chars of ms timestamp then 16 of randomness. Sorts by time. */
export type ItemId = string & { readonly [itemIdBrand]: 'cairn-id' }

// -------------------------------------------------------------- capture-side types

export type ItemKind = 'text' | 'richtext' | 'image' | 'files'
export type PasteboardHint = 'concealed' | 'transient' | 'auto-generated' | 'password-manager'
export type AgentPlatform = 'macos' | 'win32' | 'linux'

export interface SourceApp {
  readonly bundleId: string | null
  readonly name: string | null
  readonly confidence: 'heuristic' | 'unknown'
}

/** A representation with its bytes in memory. The wire form is `Rep` in ./agent.ts. */
export interface ResolvedRep {
  readonly mime: string
  readonly uti: string | null
  readonly bytes: Uint8Array
  readonly byteLength: number
  readonly sha256: ContentHash
}

/** What `privacy.classify` is given. No clock, no I/O, no bytes it does not need. */
export interface Snapshot {
  readonly reps: readonly ResolvedRep[]
  readonly primaryText: string | null
  readonly kind: ItemKind
  readonly hints: readonly PasteboardHint[]
  readonly sourceApp: SourceApp | null
  readonly totalBytes: number
}

/** What `capture` emits and `history.ingest` consumes. At most one per clipboard change. */
export interface Candidate {
  readonly reps: readonly ResolvedRep[]
  readonly kind: ItemKind
  readonly contentHash: ContentHash        // over the PRIMARY representation's bytes only
  readonly primaryText: string | null
  readonly hints: readonly PasteboardHint[]
  readonly sourceApp: SourceApp | null
  readonly thumbnailJpeg: Uint8Array | null
  readonly changeToken: string
  readonly capturedAt: number              // from the injected Clock
}

// -------------------------------------------------------------- domain and store types

export type Flag =
  | 'secret'          // a detector fired
  | 'concealed'       // the OS said so, before any byte was read
  | 'transient'       // org.nspasteboard.TransientType
  | 'auto-generated'  // org.nspasteboard.AutoGeneratedType — usually our own write
  | 'excluded'        // app exclusion list matched (M2 sets this; M1 only honours it)
  | 'no-sync'         // user marked it local-only (M5+ sets this; M1 only honours it)
  | 'cut'             // Windows Preferred DropEffect == 2 (M4)

/** assertSyncable throws for any of these. */
export const NON_SYNCABLE_FLAGS = ['secret', 'concealed', 'excluded', 'no-sync'] as const

export type DetectorName =
  | 'pem-private-key' | 'aws-access-key' | 'github-token' | 'openai-key' | 'anthropic-key'
  | 'slack-token' | 'stripe-live-key' | 'google-api-key' | 'jwt' | 'high-entropy'

export interface MaskSpan {
  readonly start: number          // UTF-16 code-unit offset into the RAW text
  readonly end: number            // exclusive
  readonly detector: DetectorName
}

export interface RepRef {
  readonly mime: string
  readonly uti: string | null
  readonly byteLength: number
  readonly sha256: ContentHash
  readonly blobId: BlobId
}

export interface Item {
  readonly id: ItemId
  readonly kind: ItemKind
  readonly contentHash: ContentHash
  /** Masked at ingest. For a secret this is `AKIA••••A7QD`, never the raw value. */
  readonly preview: string
  readonly previewTruncated: boolean
  readonly maskSpans: readonly MaskSpan[]
  readonly flags: readonly Flag[]
  readonly repRefs: readonly RepRef[]
  readonly thumbnailBlobId: BlobId | null
  readonly sourceApp: SourceApp | null
  readonly byteLength: number              // sum of repRefs[].byteLength
  readonly createdAt: number
  readonly updatedAt: number
  readonly pinned: boolean
  /** createdAt + SECRET_TTL_MS for secret-flagged items, else null. */
  readonly expiresAt: number | null
}

export interface ItemPatch {
  readonly updatedAt: number
  readonly pinned?: boolean
  readonly expiresAt?: number | null
}

export type DeleteReason =
  | 'user' | 'retention-count' | 'retention-age' | 'retention-bytes' | 'secret-ttl' | 'rekey'

export type StoreEvent =
  | { readonly kind: 'ITEM_ADDED'; readonly seq: number; readonly at: number; readonly item: Item }
  | { readonly kind: 'ITEM_UPDATED'; readonly seq: number; readonly at: number; readonly id: ItemId; readonly patch: ItemPatch }
  | { readonly kind: 'ITEM_DELETED'; readonly seq: number; readonly at: number; readonly id: ItemId; readonly reason: DeleteReason }
  | { readonly kind: 'CHECKPOINT'; readonly seq: number; readonly at: number; readonly maxSeq: number; readonly liveItemCount: number; readonly watermarks: Readonly<Record<string, number>> }

export type StoreEventKind = StoreEvent['kind']

export interface ScoredItem {
  readonly item: Item
  readonly score: number
  /**
   * FLAT array of alternating [start, end) UTF-16 offsets into `item.preview`, exactly as
   * ufuzzy's `info.ranges[n]` produces it. NOT an array of pairs.
   */
  readonly ranges: readonly number[]
}

export type KeyringMode = 'os-keyring' | 'passphrase' | 'locked'

// -------------------------------------------------------------- privacy API shapes

export interface PrivacyRules {
  readonly detectors: readonly DetectorName[]     // default: all ten
  readonly honourHints: boolean                   // default true; false only in tests
  readonly excludedBundleIds: readonly string[]   // always [] in M1
}

export interface Classification {
  readonly action: 'record' | 'skip'
  readonly flags: readonly Flag[]
  readonly reason: string
}

// -------------------------------------------------------------- the agent's public surface

export type Unsub = () => void

export interface AgentEventMap {
  'clipboard.changed': ClipboardChangedPayload
  'rep.chunk': RepChunkPayload
  'hotkey.fired': HotkeyFiredPayload
  log: AgentLogPayload
}

/**
 * The interface `@cairn/agent-host` implements and every consumer depends on. `start()` returns
 * a bare promise that REJECTS on spawn failure — it is called once, at composition, and a
 * failure there is fatal, not a value to thread. Every other call returns `Result<T>`.
 */
export interface ClipboardAgent {
  start(): Promise<AgentCapabilities>
  request<M extends AgentMethod>(
    method: M,
    params: AgentParams<M>,
    timeoutMs?: number,
  ): Promise<Result<AgentResult<M>>>
  on<E extends keyof AgentEventMap>(event: E, cb: (payload: AgentEventMap[E]) => void): Unsub
  dispose(): Promise<void>
}

/**
 * The POST-reassembly form. The host has already turned every wire `Rep` into a `ResolvedRep`,
 * so no consumer of `ClipboardAgent` ever sees `repId`, `inline` or a chunk.
 */
export interface ClipboardChangedPayload {
  readonly changeCount: number
  readonly changeToken: string          // String(changeCount) on macOS
  readonly hints: readonly PasteboardHint[]
  readonly reps: readonly ResolvedRep[]
  readonly sourceApp: SourceApp | null
  readonly droppedReps: readonly { readonly mime: string; readonly code: ErrorCode }[]
}

/** Carries NO bytes. It exists only so a progress indicator and the tests can observe chunking. */
export interface RepChunkPayload {
  readonly repId: string
  readonly seq: number
  readonly final: boolean
}

export interface HotkeyFiredPayload {
  readonly accelerator: string
  readonly focusToken: string
  readonly firedAt: number
}

/** No `fields`: the agent is not trusted to keep clipboard content out of them, so the host
 *  logs the level and the event id and drops the rest. */
export interface AgentLogPayload {
  readonly level: LogLevel
  readonly event: string
}
