// GENERATED FILE — DO NOT EDIT.
//
// Emitted by tools/gen-agent-types.ts from the zod schemas in packages/protocol/src/agent.ts.
// Regenerate with `npm run gen:agent-types`. tools/gen-agent-types.test.ts fails if this file is
// stale, so a renamed field on the TypeScript side becomes a Swift compile error here rather than a
// silent runtime mismatch across the stdio pipe.

import Foundation

/// The wire major this agent speaks. Any other value must fail to parse.
let protocolVersion = 1

/// Every request the host may send.
enum AgentMethod: String, Codable, Equatable, Sendable, CaseIterable {
    case hello = "hello"
    case watchStart = "watch.start"
    case watchStop = "watch.stop"
    case read = "read"
    case write = "write"
    case hotkeyRegister = "hotkey.register"
    case hotkeyUnregister = "hotkey.unregister"
    case shutdown = "shutdown"
}

/// Every event the agent may emit.
enum AgentEventName: String, Codable, Equatable, Sendable, CaseIterable {
    case clipboardChanged = "clipboard.changed"
    case repChunk = "rep.chunk"
    case hotkeyFired = "hotkey.fired"
    case log = "log"
}

/// A single `log` event field value. Metadata only — never clipboard bytes.
enum AgentLogValue: Codable, Equatable, Sendable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case null

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Double.self) {
            self = .number(value)
        } else {
            self = .string(try container.decode(String.self))
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}

struct AgentCapabilities: Codable, Equatable, Sendable {
    var agent: AgentCapabilitiesAgent
    var agentVersion: String
    var chunkThresholdBytes: Int
    var clipboardWatch: AgentCapabilitiesClipboardWatch
    var concealedTypeHints: Bool
    var focusApp: Bool
    var hotkey: AgentCapabilitiesHotkey
    var maxRepBytes: Int
    var missingTools: [String]?
    var paste: AgentCapabilitiesPaste
    var platformVersion: String
    var tier: AgentCapabilitiesTier
    var wireMajor: Int
}

enum AgentCapabilitiesAgent: String, Codable, Equatable, Sendable, CaseIterable {
    case macos = "macos"
    case win32 = "win32"
    case linux = "linux"
}

enum AgentCapabilitiesClipboardWatch: String, Codable, Equatable, Sendable, CaseIterable {
    case changecountPoll = "changecount-poll"
    case sequencePoll = "sequence-poll"
    case xfixes = "xfixes"
    case wlPasteWatch = "wl-paste-watch"
    case focusOnly = "focus-only"
    case none = "none"
}

enum AgentCapabilitiesHotkey: String, Codable, Equatable, Sendable, CaseIterable {
    case carbon = "carbon"
    case win32Hotkey = "win32-hotkey"
    case portal = "portal"
    case electron = "electron"
    case none = "none"
}

enum AgentCapabilitiesPaste: String, Codable, Equatable, Sendable, CaseIterable {
    case cgevent = "cgevent"
    case sendinput = "sendinput"
    case ydotool = "ydotool"
    case none = "none"
}

enum AgentCapabilitiesTier: String, Codable, Equatable, Sendable, CaseIterable {
    case a = "A"
    case b = "B"
    case c = "C"
    case d = "D"
}

struct AgentError: Codable, Equatable, Sendable {
    var code: String
    var message: String
}

struct ClipboardChangedData: Codable, Equatable, Sendable {
    var attributionConfidence: ClipboardChangedDataAttributionConfidence
    var changeCount: Int
    var frontmostBundleId: String?
    var frontmostName: String?
    var hints: [Hint]?
    var reps: [Rep]
}

enum ClipboardChangedDataAttributionConfidence: String, Codable, Equatable, Sendable, CaseIterable {
    case heuristic = "heuristic"
    case unknown = "unknown"
}

struct HelloParams: Codable, Equatable, Sendable {
    var hostVersion: String
}

typealias HelloResult = AgentCapabilities

/// Values of the Hint wire enum.
enum Hint: String, Codable, Equatable, Sendable, CaseIterable {
    case concealed = "concealed"
    case transient = "transient"
    case autoGenerated = "auto-generated"
    case passwordManager = "password-manager"
}

struct HotkeyFiredData: Codable, Equatable, Sendable {
    var accelerator: String
    var firedAt: Int
    var focusToken: String
}

struct HotkeyRegisterParams: Codable, Equatable, Sendable {
    var accelerator: String
}

struct HotkeyRegisterResult: Codable, Equatable, Sendable {
    var accelerator: String
    var bound: Bool
}

struct HotkeyUnregisterParams: Codable, Equatable, Sendable {}

struct HotkeyUnregisterResult: Codable, Equatable, Sendable {
    var bound: Bool
}

struct LogData: Codable, Equatable, Sendable {
    var event: String
    var fields: [String: AgentLogValue]?
    var level: LogDataLevel
}

enum LogDataLevel: String, Codable, Equatable, Sendable, CaseIterable {
    case debug = "debug"
    case info = "info"
    case warn = "warn"
    case error = "error"
}

struct ReadParams: Codable, Equatable, Sendable {
    var changeCount: Int
}

struct ReadResult: Codable, Equatable, Sendable {
    var changeCount: Int
    var hints: [Hint]?
    var reps: [Rep]
}

struct Rep: Codable, Equatable, Sendable {
    var byteLength: Int
    var inline: Data?
    var mime: String
    var repId: String?
    var sha256: String
    var uti: String?
}

struct RepChunkData: Codable, Equatable, Sendable {
    var b64: Data
    var final: Bool
    var repId: String
    var seq: Int
}

struct ShutdownParams: Codable, Equatable, Sendable {}

struct ShutdownResult: Codable, Equatable, Sendable {
    var bye: Bool
}

struct WatchStartParams: Codable, Equatable, Sendable {
    var intervalMs: Int
}

struct WatchStartResult: Codable, Equatable, Sendable {
    var intervalMs: Int
    var watching: Bool
}

struct WatchStopParams: Codable, Equatable, Sendable {}

struct WatchStopResult: Codable, Equatable, Sendable {
    var watching: Bool
}

struct WriteParams: Codable, Equatable, Sendable {
    var reps: [WriteParamsRepsItem]
    var transient: Bool
}

struct WriteParamsRepsItem: Codable, Equatable, Sendable {
    var b64: Data
    var mime: String
    var uti: String?
}

struct WriteResult: Codable, Equatable, Sendable {
    var changeToken: String
}
