import AppKit
import CryptoKit
import Foundation

/// The three nspasteboard.org marker UTIs. Mirrors UTI_CONCEALED / UTI_TRANSIENT /
/// UTI_AUTO_GENERATED in packages/protocol/src/constants.ts — these are third-party well-known
/// strings rather than Cairn names, so both sides of the pipe spell them out.
enum HintUTI {
  static let concealed = "org.nspasteboard.ConcealedType"
  static let transient = "org.nspasteboard.TransientType"
  static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
  static let all = [concealed, transient, autoGenerated]
}

/// UTI -> MIME allowlist. Anything not listed here is never read: an allowlist means a new OS UTI
/// cannot silently start flowing bytes into the history.
enum RepFilter {
  static let plainText = "public.utf8-plain-text"
  static let html = "public.html"
  static let rtf = "public.rtf"
  static let fileURL = "public.file-url"
  static let png = "public.png"
  static let tiff = "public.tiff"
  static let pdf = "com.adobe.pdf"
  static let chromeSourceURL = "org.chromium.source-url"

  struct Plan: Equatable {
    let uti: String
    /// The mime we publish. For `public.tiff` this is `image/png`, because we convert at capture.
    let mime: String
    /// True only for public.tiff: the bytes are transcoded before they leave the agent.
    let tiffToPng: Bool
  }

  /// PURE. Given ONE pasteboard item's UTIs in the order the OS offered them, returns what to read
  /// from that item, in the frozen order. Image preference is png > tiff > pdf, per spec §10: a
  /// promised `public.tiff` from Photoshop renders synchronously and can block, balloon, or come
  /// back nil.
  static func plan(forItemTypes types: [String]) -> [Plan] {
    let has = Set(types)
    var out: [Plan] = []
    if has.contains(plainText) { out.append(Plan(uti: plainText, mime: "text/plain", tiffToPng: false)) }
    if has.contains(html) { out.append(Plan(uti: html, mime: "text/html", tiffToPng: false)) }
    if has.contains(rtf) { out.append(Plan(uti: rtf, mime: "text/rtf", tiffToPng: false)) }
    if has.contains(fileURL) { out.append(Plan(uti: fileURL, mime: "text/uri-list", tiffToPng: false)) }
    if has.contains(png) {
      out.append(Plan(uti: png, mime: "image/png", tiffToPng: false))
    } else if has.contains(tiff) {
      out.append(Plan(uti: tiff, mime: "image/png", tiffToPng: true))
    } else if has.contains(pdf) {
      out.append(Plan(uti: pdf, mime: "application/pdf", tiffToPng: false))
    }
    if has.contains(chromeSourceURL) {
      out.append(Plan(uti: chromeSourceURL, mime: "text/x-source-url", tiffToPng: false))
    }
    return out
  }

  /// PURE. TIFF -> PNG. Runs with no window server and no NSApplication.
  static func tiffToPng(_ data: Data) -> Data? {
    guard let rep = NSBitmapImageRep(data: data) else { return nil }
    return rep.representation(using: .png, properties: [:])
  }
}

/// PURE. `sha256-<43 chars base64url>`, byte-identical to @cairn/protocol's contentHash().
func contentHash(_ bytes: Data) -> String {
  let digest = Data(SHA256.hash(data: bytes))
  let b64 = digest.base64EncodedString()
    .replacingOccurrences(of: "+", with: "-")
    .replacingOccurrences(of: "/", with: "_")
    .replacingOccurrences(of: "=", with: "")
  return "sha256-" + b64
}

/// A wedged promised read cannot be cancelled from inside the process, so the watchdog escalates to
/// the only lever that exists: exit, and let @cairn/agent-host restart us with backoff (spec §10).
enum ReadWatchdog {
  enum Action: Equatable { case ignore, warn, killProcess }

  private static let lock = NSLock()
  private static var startedAt: DispatchTime?
  private static var strikes = 0
  private static var timer: DispatchSourceTimer?

  /// PURE. The whole escalation policy, so it can be asserted without wedging a real pasteboard.
  static func decide(elapsedMs: Int, strikes: Int) -> Action {
    if elapsedMs <= AGENT_REQUEST_TIMEOUT_MS { return .ignore }
    return strikes + 1 >= 2 ? .killProcess : .warn
  }

  static func begin() { lock.lock(); startedAt = .now(); lock.unlock() }
  static func end() { lock.lock(); startedAt = nil; strikes = 0; lock.unlock() }

  static func start() {
    let q = DispatchQueue(label: "app.cairn.agent.watchdog")
    let t = DispatchSource.makeTimerSource(queue: q)
    t.schedule(deadline: .now() + .milliseconds(500), repeating: .milliseconds(500), leeway: .milliseconds(100))
    t.setEventHandler { check() }
    t.activate()
    timer = t
  }

  private static func check() {
    lock.lock()
    let began = startedAt
    let seen = strikes
    lock.unlock()
    guard let began else { return }
    let elapsedMs = Int((DispatchTime.now().uptimeNanoseconds - began.uptimeNanoseconds) / 1_000_000)
    switch decide(elapsedMs: elapsedMs, strikes: seen) {
    case .ignore:
      return
    case .warn:
      lock.lock(); strikes += 1; lock.unlock()
      Out.log(.warn, "pasteboard.read-wedged", ["elapsedMs": .number(Double(elapsedMs))])
    case .killProcess:
      Out.log(.error, "pasteboard.read-wedged-fatal", ["elapsedMs": .number(Double(elapsedMs))])
      Out.stderrLine("cairn-agent: pasteboard read wedged for \(elapsedMs)ms; exiting 75 so the host restarts us")
      exit(75)
    }
  }
}

/// Frontmost app, cached. NSWorkspace notifications arrive on main and are marshalled onto the
/// pasteboard queue (spec §4 thread discipline), so a read never touches NSWorkspace itself.
enum Frontmost {
  private static let lock = NSLock()
  private static var bundleId: String?
  private static var name: String?

  static func snapshot() -> (bundleId: String?, name: String?) {
    lock.lock(); defer { lock.unlock() }
    return (bundleId, name)
  }

  private static func set(_ app: NSRunningApplication?) {
    lock.lock()
    bundleId = app?.bundleIdentifier
    name = app?.localizedName
    lock.unlock()
  }

  /// MUST be called on the main thread.
  static func startObserving() {
    set(NSWorkspace.shared.frontmostApplication)
    NSWorkspace.shared.notificationCenter.addObserver(
      forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main
    ) { note in
      let app = note.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication
      Pasteboard.queue.async { set(app) }
    }
  }
}

enum Pasteboard {
  /// THE one queue. Every NSPasteboard call in this process happens here and nowhere else:
  /// NSPasteboard's thread safety is undocumented by Apple and is a known crash and stale-read
  /// source.
  static let queue = DispatchQueue(label: "app.cairn.agent.pasteboard")

  private static let hintTypes = HintUTI.all.map { NSPasteboard.PasteboardType($0) }

  static func changeCount() -> Int { NSPasteboard.general.changeCount }

  /// Probes the marker UTIs BEFORE any byte is read. Reading first would defeat the entire point:
  /// the bytes of a concealed item must never enter this process at all.
  static func probeHints() -> [Hint] {
    let pb = NSPasteboard.general
    guard pb.availableType(from: hintTypes) != nil else { return [] }   // one cheap call, usually nil
    var hints: [Hint] = []
    if pb.availableType(from: [NSPasteboard.PasteboardType(HintUTI.concealed)]) != nil { hints.append(.concealed) }
    if pb.availableType(from: [NSPasteboard.PasteboardType(HintUTI.transient)]) != nil { hints.append(.transient) }
    if pb.availableType(from: [NSPasteboard.PasteboardType(HintUTI.autoGenerated)]) != nil { hints.append(.autoGenerated) }
    return hints
  }

  /// PURE. The one place that decides whether bytes may be read at all.
  static func mayReadBytes(hints: [Hint]) -> Bool { !hints.contains(.concealed) }

  struct ReadOutcome {
    let changeCount: Int
    let hints: [Hint]
    let reps: [Rep]
    let streams: [Chunker.Stream]
  }

  /// MUST run on `queue`. One explicit autorelease pool per read: NSPasteboard hands back
  /// autoreleased NSData, and a command-line process has no per-event-loop pool to drain them.
  static func read() -> ReadOutcome {
    autoreleasepool {
      let pb = NSPasteboard.general
      let cc = pb.changeCount
      let hints = probeHints()
      guard mayReadBytes(hints: hints) else {
        Out.log(.info, "pasteboard.concealed-skipped", ["changeCount": .number(Double(cc))])
        return ReadOutcome(changeCount: cc, hints: hints, reps: [], streams: [])
      }

      ReadWatchdog.begin()
      defer { ReadWatchdog.end() }

      var reps: [Rep] = []
      var streams: [Chunker.Stream] = []
      var seenMimes = Set<String>()
      var fileURLs: [String] = []
      var skipped = 0

      // pb.pasteboardItems, never pb.types: [verified] on this machine a single copied string
      // reports `["public.utf8-plain-text"]` per item but `["public.utf8-plain-text",
      // "NSStringPboardType"]` from pb.types, and persisting that alias would fabricate a
      // representation the source app never offered.
      for item in pb.pasteboardItems ?? [] {
        let offered = item.types.map(\.rawValue)
        for plan in RepFilter.plan(forItemTypes: offered) {
          if plan.uti == RepFilter.fileURL {
            if let s = item.string(forType: NSPasteboard.PasteboardType(RepFilter.fileURL)) {
              fileURLs.append(s)
            }
            continue
          }
          if seenMimes.contains(plan.mime) { continue }
          guard var bytes = item.data(forType: NSPasteboard.PasteboardType(plan.uti)) else {
            // A promised representation whose owner has quit renders as nil. Not an error.
            Out.log(.info, "pasteboard.rep-nil", ["uti": .string(plan.uti)])
            continue
          }
          if plan.tiffToPng {
            guard let png = RepFilter.tiffToPng(bytes) else {
              Out.log(.warn, "pasteboard.tiff-convert-failed", ["bytes": .number(Double(bytes.count))])
              continue
            }
            bytes = png
          }
          if bytes.count > MAX_REP_BYTES {
            Out.log(.warn, "pasteboard.rep-too-large", ["mime": .string(plan.mime), "bytes": .number(Double(bytes.count))])
            skipped += 1
            continue
          }
          seenMimes.insert(plan.mime)
          let prepared = Chunker.prepare(mime: plan.mime, uti: plan.uti, bytes: bytes)
          reps.append(prepared.rep)
          if let s = prepared.stream { streams.append(s) }
        }
      }

      if !fileURLs.isEmpty, !seenMimes.contains("text/uri-list") {
        // One URI per line, LF-terminated including the last. @cairn/capture canonicalises it.
        let bytes = Data((fileURLs.map { $0 + "\n" }.joined()).utf8)
        let prepared = Chunker.prepare(mime: "text/uri-list", uti: RepFilter.fileURL, bytes: bytes)
        reps.append(prepared.rep)
        if let s = prepared.stream { streams.append(s) }
      }

      if skipped > 0 { Out.log(.warn, "pasteboard.reps-skipped", ["count": .number(Double(skipped))]) }
      return ReadOutcome(changeCount: cc, hints: hints, reps: reps, streams: streams)
    }
  }
}
