import AppKit
import Foundation

enum Writer {
  /// MIME -> UTI for the reps we can write back. The host may override per rep with `uti`.
  static let utiForMime: [String: String] = [
    "text/plain": "public.utf8-plain-text",
    "text/html": "public.html",
    "text/rtf": "public.rtf",
    "image/png": "public.png",
    "application/pdf": "com.adobe.pdf",
    "text/uri-list": "public.file-url",
  ]

  /// MUST run on Pasteboard.queue.
  ///
  /// Returns the changeCount the write caused. That number IS the self-write suppression token:
  /// @cairn/capture ignores exactly this changeCount, which is how pressing Enter in the palette
  /// does not re-record the item you just recalled.
  ///
  /// `transient: true` additionally marks org.nspasteboard.TransientType and AutoGeneratedType so
  /// every other clipboard manager on the machine skips it too. M1 never passes true — recall puts
  /// the item on the clipboard to keep. M2's paste path does.
  ///
  /// The parameter type is the generated `WriteParamsRepsItem` — there is no hand-written `WriteRep`.
  /// `WriteParamsRepsItem.b64` is `Data`, so JSONDecoder already base64-DECODED it and there is no
  /// `Data(base64Encoded:)` call here: a malformed base64 string failed the decode and the whole
  /// `write` was answered `E_BAD_PARAMS` in main.swift before this function was ever reached.
  static func write(reps: [WriteParamsRepsItem], transient: Bool) -> Int {
    autoreleasepool {
      var items: [NSPasteboardItem] = []
      var uriListURLs: [String] = []
      let primary = NSPasteboardItem()
      items.append(primary)

      for rep in reps {
        if rep.mime == "text/uri-list" {
          // A multi-file copy is N pasteboard items, one public.file-url each — that is the only
          // shape Finder accepts.
          let text = String(decoding: rep.b64, as: UTF8.self)
          uriListURLs = text.split(whereSeparator: \.isNewline).map(String.init)
          continue
        }
        let uti = rep.uti ?? utiForMime[rep.mime] ?? rep.mime
        if !primary.setData(rep.b64, forType: NSPasteboard.PasteboardType(uti)) {
          Out.log(.warn, "write.set-data-refused", ["mime": .string(rep.mime), "uti": .string(uti)])
        }
      }

      for (index, url) in uriListURLs.enumerated() {
        let target = index == 0 ? primary : NSPasteboardItem()
        target.setString(url, forType: NSPasteboard.PasteboardType(RepFilter.fileURL))
        if index > 0 { items.append(target) }
      }

      if transient {
        primary.setData(Data(), forType: NSPasteboard.PasteboardType(HintUTI.transient))
        primary.setData(Data(), forType: NSPasteboard.PasteboardType(HintUTI.autoGenerated))
      }

      let pb = NSPasteboard.general
      // clearContents() increments changeCount and returns the new value; writeObjects() does not
      // increment it again, so this return value IS the final changeCount.
      // [verified] clearContents() returned 364 and pb.changeCount was still 364 after writeObjects.
      let token = pb.clearContents()
      if !pb.writeObjects(items) {
        Out.log(.error, "write.write-objects-failed", ["repCount": .number(Double(reps.count))])
      }
      return token
    }
  }
}
