import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import * as z from 'zod'
import * as protocol from '@cairn/protocol'
import {
  GENERATED_PATH,
  GenError,
  agentGenInput,
  generateSwift,
  type GenInput,
  type ProtocolSchemas,
} from './gen-agent-types'

const input = agentGenInput(protocol as unknown as ProtocolSchemas)
const committed = readFileSync(GENERATED_PATH, 'utf8')

describe('the committed Swift file is exactly what the generator emits', () => {
  it('is byte-identical, so a codegen change always shows up as a reviewable diff', () => {
    // If this fails, run `npm run gen:agent-types` and commit the result. Never hand-edit.
    expect(generateSwift(input)).toBe(committed)
  })

  it('is deterministic: generating twice produces the same bytes', () => {
    expect(generateSwift(input)).toBe(generateSwift(input))
  })

  it('carries a DO-NOT-EDIT header and imports nothing but Foundation', () => {
    expect(committed.startsWith('// GENERATED FILE — DO NOT EDIT.')).toBe(true)
    expect(committed.match(/^import .*$/gm)).toEqual(['import Foundation'])
    expect(committed.endsWith('\n')).toBe(true)
  })

  it('pins protocolVersion to WIRE_MAJOR and emits no other top-level let', () => {
    expect(committed).toContain(`let protocolVersion = ${protocol.WIRE_MAJOR}`)
    expect(committed).toContain('let protocolVersion = 1')
    // A zod schema has nowhere to hang a bare number, so the generator emits no numeric limit.
    // Task 4's Wire.swift declares the six it needs, under its own drift guard; emitting them
    // here too would be `error: invalid redeclaration of 'MAX_REP_BYTES'` at `make agent`.
    expect(committed.match(/^let /gm)).toHaveLength(1)
    for (const name of ['MAX_LINE_BYTES', 'MAX_REP_BYTES', 'CHUNK_PAYLOAD_BYTES']) {
      expect(committed).not.toContain(`let ${name}`)
    }
  })
})

describe('the generated Swift matches the zod schemas field for field', () => {
  it('declares one AgentMethod case per request method, with the wire string as raw value', () => {
    for (const [method] of input.requests) expect(committed).toContain(`= "${method}"`)
    expect(committed).toContain('case watchStart = "watch.start"')
    expect(committed).toContain('case hotkeyUnregister = "hotkey.unregister"')
  })

  it('declares one AgentEventName case per event', () => {
    expect(committed).toContain('case clipboardChanged = "clipboard.changed"')
    expect(committed).toContain('case repChunk = "rep.chunk"')
  })

  it('maps zod base64 fields to Swift Data, which JSONCoder encodes as base64 for free', () => {
    // Task 4's Chunker.split therefore returns [Data] and no Swift file calls a base64 API for
    // a payload. Changing this to String breaks every construction in six Swift files.
    expect(committed).toContain('var b64: Data')
    expect(committed).toContain('var inline: Data?')
  })

  it('maps z.int() to Int and z.boolean() to Bool', () => {
    expect(committed).toContain('var byteLength: Int')
    expect(committed).toContain('var final: Bool')
  })

  it('maps a nullable-with-default field to a Swift Optional', () => {
    expect(committed).toContain('var uti: String?')
    expect(committed).toContain('var frontmostBundleId: String?')
  })

  it('aliases HelloResult rather than emitting a second AgentCapabilities struct', () => {
    expect(committed).toContain('typealias HelloResult = AgentCapabilities')
    expect(committed.match(/struct AgentCapabilities:/g)).toHaveLength(1)
    expect(committed).not.toContain('struct HelloResult')
  })

  it('emits shared named types once, referenced by every user', () => {
    expect(committed.match(/^struct Rep: /gm)).toHaveLength(1)
    expect(committed.match(/^enum Hint: /gm)).toHaveLength(1)
    expect(committed).toContain('var reps: [Rep]')
    expect(committed).toContain('var hints: [Hint]?')
    // `write`'s rep element is an INLINE object, so it is named after its owner. Task 4's
    // Writer.swift takes `[WriteParamsRepsItem]` and hand-declares no twin of it.
    expect(committed.match(/^struct WriteParamsRepsItem: /gm)).toHaveLength(1)
    expect(committed).toContain('var reps: [WriteParamsRepsItem]')
  })

  it('camelCases kebab-case enum members and keeps the wire string verbatim', () => {
    expect(committed).toContain('case autoGenerated = "auto-generated"')
    expect(committed).toContain('case changecountPoll = "changecount-poll"')
    expect(committed).toContain('case win32Hotkey = "win32-hotkey"')
  })

  it('sorts struct fields alphabetically, so reordering keys in agent.ts is not a diff', () => {
    const straight = z.object({ zulu: z.string(), alpha: z.int(), mike: z.boolean() })
    const shuffled = z.object({ mike: z.boolean(), zulu: z.string(), alpha: z.int() })
    const gen = (params: z.ZodType): string =>
      generateSwift({ wireMajor: 1, named: [], requests: [['probe', params]], results: [['probe', params]], events: [] })
    expect(gen(straight)).toBe(gen(shuffled))
    expect(gen(straight)).toContain(
      'struct ProbeParams: Codable, Equatable, Sendable {\n    var alpha: Int\n    var mike: Bool\n    var zulu: String\n}',
    )
  })
})

describe('renaming a field changes the output — this is the drift alarm', () => {
  const renamed: GenInput = {
    ...input,
    requests: input.requests.map(([method, params]) =>
      method === 'hello' ? ([method, z.object({ hostVer: z.string() })] as const) : ([method, params] as const),
    ),
  }

  it('produces different bytes from the committed file', () => {
    expect(generateSwift(renamed)).not.toBe(committed)
  })

  it('emits the new field name and drops the old one', () => {
    const out = generateSwift(renamed)
    expect(out).toContain('var hostVer: String')
    expect(out).not.toContain('var hostVersion: String')
    expect(committed).toContain('var hostVersion: String')
  })
})

describe('the generator fails loudly rather than emitting something wrong', () => {
  const genWith = (params: z.ZodType): string =>
    generateSwift({ wireMajor: 1, named: [], requests: [['probe', params]], results: [['probe', params]], events: [] })

  it('throws GenError, naming the zod type and the field path, for an unmappable type', () => {
    expect(() => genWith(z.object({ weird: z.bigint() }))).toThrow(GenError)
    expect(() => genWith(z.object({ weird: z.bigint() }))).toThrow(
      "cannot map zod type 'bigint' at ProbeParams.weird",
    )
  })

  it('throws for z.unknown(), z.any(), z.date(), z.map() and z.tuple() too', () => {
    for (const [label, schema] of [
      ['unknown', z.unknown()],
      ['any', z.any()],
      ['date', z.date()],
      ['map', z.map(z.string(), z.string())],
      ['tuple', z.tuple([z.string()])],
    ] as const) {
      expect(() => genWith(z.object({ weird: schema })), label).toThrow(GenError)
    }
  })

  it('throws for a record whose value type is not the log-metadata union', () => {
    expect(() => genWith(z.object({ bag: z.record(z.string(), z.string()) }))).toThrow(
      /only the log-metadata record/,
    )
  })

  it('accepts the log-metadata record and maps it to [String: AgentLogValue]', () => {
    const bag = z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()]))
    expect(genWith(z.object({ fields: bag }))).toContain('var fields: [String: AgentLogValue]')
  })

  it('throws when two different shapes collide on one Swift type name', () => {
    expect(() =>
      generateSwift({
        wireMajor: 1,
        named: [],
        requests: [
          ['probe', z.object({ a: z.string() })],
          ['probe', z.object({ b: z.string() })],
        ],
        results: [],
        events: [],
      }),
    ).toThrow(/both want the Swift type name 'ProbeParams'/)
  })

  it('throws when AgentResultSchema is missing an entry for a request method', () => {
    expect(() =>
      agentGenInput({
        ...(protocol as unknown as ProtocolSchemas),
        AgentResultSchema: { hello: z.object({}) },
      }),
    ).toThrow("AgentResultSchema has no entry for method 'watch.start'")
  })

  it('throws when handed something that is not a discriminated union', () => {
    expect(() =>
      agentGenInput({
        ...(protocol as unknown as ProtocolSchemas),
        AgentEventSchema: z.object({ nope: z.string() }),
      }),
    ).toThrow(/is not a non-empty union/)
  })
})
