/**
 * zod -> Swift codegen. Emits `agents/macos/Sources/AgentProtocol.generated.swift` from the zod
 * schemas in `packages/protocol/src/agent.ts`, so a field rename on the TypeScript side becomes
 * a Swift COMPILE error instead of a runtime "why is uti always nil".
 *
 * Run: `npm run gen:agent-types`. The emitted file is committed; `gen-agent-types.test.ts` fails
 * if it is stale, which is what makes a codegen change visible in review.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { registerHooks } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import * as z from 'zod'

// ------------------------------------------------------------------------------- errors

/** Thrown when a schema uses a construct this generator refuses to guess at. */
export class GenError extends Error {
  override readonly name = 'GenError'
}

// ------------------------------------------------------------------- zod introspection

interface ZodDefLike {
  readonly type: string
  readonly format?: string
  readonly innerType?: z.ZodType
  readonly element?: z.ZodType
  readonly shape?: Readonly<Record<string, z.ZodType>>
  readonly entries?: Readonly<Record<string, string | number>>
  readonly values?: readonly unknown[]
  readonly keyType?: z.ZodType
  readonly valueType?: z.ZodType
  readonly options?: readonly z.ZodType[]
}

/** zod 4 exposes every schema's internals at `_zod.def`; `.type` is the discriminator we map on. */
const defOf = (s: z.ZodType): ZodDefLike => s._zod.def as unknown as ZodDefLike

// ------------------------------------------------------------------------- Swift naming

const SWIFT_RESERVED = new Set([
  'associatedtype', 'as', 'any', 'async', 'await', 'break', 'case', 'catch', 'class', 'continue',
  'default', 'defer', 'deinit', 'do', 'else', 'enum', 'extension', 'false', 'fileprivate', 'for',
  'func', 'guard', 'if', 'import', 'in', 'indirect', 'init', 'inout', 'internal', 'is', 'lazy',
  'let', 'mutating', 'nil', 'nonmutating', 'open', 'operator', 'override', 'private', 'protocol',
  'public', 'repeat', 'required', 'rethrows', 'return', 'self', 'Self', 'some', 'static', 'struct',
  'subscript', 'super', 'switch', 'throw', 'throws', 'true', 'try', 'typealias', 'var', 'where',
  'while',
])

/** `watch.start` -> `WatchStart`, `auto-generated` -> `AutoGenerated`. */
function pascal(s: string): string {
  return s
    .split(/[.\-_ ]+/)
    .filter((part) => part.length > 0)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

/** `watch.start` -> `watchStart`, `A` -> `a`. */
function camel(s: string): string {
  const p = pascal(s)
  return p.charAt(0).toLowerCase() + p.slice(1)
}

/** Swift keywords are legal identifiers when backticked, so escape rather than mangle. */
function ident(name: string): string {
  return SWIFT_RESERVED.has(name) ? `\`${name}\`` : name
}

// -------------------------------------------------------------------------- the emitter

interface Emitter {
  /** Swift type name -> full declaration text. */
  readonly decls: Map<string, string>
  /** schema identity -> Swift type name, seeded from GenInput.named. */
  readonly named: Map<z.ZodType, string>
}

function declare(em: Emitter, name: string, body: string): string {
  const existing = em.decls.get(name)
  if (existing !== undefined && existing !== body) {
    throw new GenError(
      `two different shapes both want the Swift type name '${name}'. Give one of them an entry in ` +
        `GenInput.named so it gets a stable, distinct name.`,
    )
  }
  em.decls.set(name, body)
  return name
}

/** Resolves one schema to a Swift type, emitting any nested declarations it needs. */
function swiftTypeFor(schema: z.ZodType, owner: string, field: string, em: Emitter): string {
  let inner = schema
  let optional = false
  for (;;) {
    const d = defOf(inner)
    if (d.type === 'optional' || d.type === 'nullable' || d.type === 'default') {
      if (d.innerType === undefined) throw new GenError(`wrapper '${d.type}' has no innerType at ${owner}.${field}`)
      optional = true
      inner = d.innerType
      continue
    }
    break
  }
  const registered = em.named.get(inner)
  const base = registered ?? baseSwiftTypeFor(inner, owner, field, em)
  return optional ? `${base}?` : base
}

function baseSwiftTypeFor(s: z.ZodType, owner: string, field: string, em: Emitter): string {
  const d = defOf(s)
  const nestedName = owner + pascal(field)
  switch (d.type) {
    case 'string':
      // Swift's JSONEncoder/JSONDecoder use base64 for `Data` by default, so a zod base64 string
      // maps to `Data` and the agent never hand-rolls a base64 call. Six Swift files in Task 4
      // are written against that, including `Chunker.split(_:payloadBytes:) -> [Data]`.
      return d.format === 'base64' ? 'Data' : 'String'
    case 'number':
      return d.format === 'safeint' || d.format === 'int32' || d.format === 'uint32' ? 'Int' : 'Double'
    case 'boolean':
      return 'Bool'
    case 'literal': {
      const values = d.values ?? []
      if (values.length !== 1) {
        throw new GenError(`literal with ${values.length} values at ${owner}.${field}; expected exactly 1`)
      }
      const v = values[0]
      if (typeof v === 'string') return 'String'
      if (typeof v === 'boolean') return 'Bool'
      if (typeof v === 'number') return Number.isInteger(v) ? 'Int' : 'Double'
      throw new GenError(`cannot map literal of JS type '${typeof v}' at ${owner}.${field}`)
    }
    case 'enum': {
      const values = Object.values(d.entries ?? {})
      if (values.length === 0) throw new GenError(`empty enum at ${owner}.${field}`)
      const cases = values.map((v) => {
        if (typeof v !== 'string') {
          throw new GenError(`cannot map non-string enum member '${String(v)}' at ${owner}.${field}`)
        }
        return `    case ${ident(camel(v))} = "${v}"`
      })
      return declare(
        em,
        nestedName,
        `enum ${nestedName}: String, Codable, Equatable, Sendable, CaseIterable {\n${cases.join('\n')}\n}`,
      )
    }
    case 'array': {
      if (d.element === undefined) throw new GenError(`array has no element schema at ${owner}.${field}`)
      return `[${swiftTypeFor(d.element, owner, `${field}Item`, em)}]`
    }
    case 'object':
      return emitStruct(nestedName, s, em)
    case 'record': {
      // The ONLY record we know how to map is the `log` event's metadata bag: string keys and a
      // string | number | boolean | null value. Anything else must be modelled explicitly.
      const keyType = d.keyType === undefined ? '?' : defOf(d.keyType).type
      const valueOptions = (d.valueType === undefined ? [] : defOf(d.valueType).options ?? [])
        .map((o) => defOf(o).type)
        .sort()
      if (keyType === 'string' && valueOptions.join(',') === 'boolean,null,number,string') {
        return '[String: AgentLogValue]'
      }
      throw new GenError(
        `cannot map record<${keyType}, ${valueOptions.join('|') || '?'}> at ${owner}.${field}; ` +
          `only the log-metadata record (string keys, string|number|boolean|null values) is supported`,
      )
    }
    default:
      throw new GenError(`cannot map zod type '${d.type}' at ${owner}.${field}`)
  }
}

function emitStruct(name: string, schema: z.ZodType, em: Emitter): string {
  const shape = defOf(schema).shape
  if (shape === undefined) throw new GenError(`object schema '${name}' has no shape`)
  // Alphabetical, so reordering keys in agent.ts does not churn the generated file.
  const keys = Object.keys(shape).sort()
  const fields = keys.map((key) => {
    const fieldSchema = shape[key]
    if (fieldSchema === undefined) throw new GenError(`field '${key}' of '${name}' is undefined`)
    return `    var ${ident(key)}: ${swiftTypeFor(fieldSchema, name, key, em)}`
  })
  const body =
    fields.length === 0
      ? `struct ${name}: Codable, Equatable, Sendable {}`
      : `struct ${name}: Codable, Equatable, Sendable {\n${fields.join('\n')}\n}`
  return declare(em, name, body)
}

// ---------------------------------------------------------------------------- the input

export interface GenInput {
  readonly wireMajor: number
  /** Schemas that must get a stable shared Swift name instead of a nested generated one. */
  readonly named: readonly (readonly [z.ZodType, string])[]
  /** `[method, paramsSchema]`, one per request the agent accepts. */
  readonly requests: readonly (readonly [string, z.ZodType])[]
  /** `[method, resultSchema]`, one per request. */
  readonly results: readonly (readonly [string, z.ZodType])[]
  /** `[event, dataSchema]`, one per event the agent emits. */
  readonly events: readonly (readonly [string, z.ZodType])[]
}

/**
 * The subset of `@cairn/protocol` this generator reads. `WIRE_MAJOR` is the only number in it:
 * a zod schema has nowhere to hang a bare limit, so the generated Swift carries no
 * `MAX_REP_BYTES` and friends. Task 4's `Wire.swift` declares those six itself, guarded by a test
 * that reads `constants.ts`; emitting them here as well would be a Swift redeclaration error.
 */
export interface ProtocolSchemas {
  readonly WIRE_MAJOR: number
  readonly HintSchema: z.ZodType
  readonly RepSchema: z.ZodType
  readonly AgentCapabilitiesSchema: z.ZodType
  readonly AgentErrorSchema: z.ZodType
  readonly AgentRequestSchema: z.ZodType
  readonly AgentEventSchema: z.ZodType
  readonly AgentResultSchema: Readonly<Record<string, z.ZodType>>
}

function unionOptions(u: z.ZodType, what: string): readonly z.ZodType[] {
  const options = defOf(u).options
  if (options === undefined || options.length === 0) {
    throw new GenError(`${what} is not a non-empty union`)
  }
  return options
}

function stringLiteral(s: z.ZodType | undefined, what: string): string {
  const v = s === undefined ? undefined : defOf(s).values?.[0]
  if (typeof v !== 'string') throw new GenError(`${what} is not a string literal`)
  return v
}

/** Derives the generator's input from the protocol module, so nothing is hand-listed twice. */
export function agentGenInput(m: ProtocolSchemas): GenInput {
  const pairs = (union: z.ZodType, discriminator: 'method' | 'event', payload: 'params' | 'data') =>
    unionOptions(union, `Agent${pascal(discriminator)}Schema`).map((option) => {
      const shape = defOf(option).shape ?? {}
      const key = stringLiteral(shape[discriminator], `${discriminator} discriminator`)
      const body = shape[payload]
      if (body === undefined) throw new GenError(`'${key}' has no ${payload} schema`)
      return [key, body] as const
    })

  const requests = pairs(m.AgentRequestSchema, 'method', 'params')
  const events = pairs(m.AgentEventSchema, 'event', 'data')
  const results = requests.map(([method]) => {
    const result = m.AgentResultSchema[method]
    if (result === undefined) throw new GenError(`AgentResultSchema has no entry for method '${method}'`)
    return [method, result] as const
  })

  return {
    wireMajor: m.WIRE_MAJOR,
    named: [
      [m.HintSchema, 'Hint'],
      [m.RepSchema, 'Rep'],
      [m.AgentCapabilitiesSchema, 'AgentCapabilities'],
      [m.AgentErrorSchema, 'AgentError'],
    ],
    requests,
    results,
    events,
  }
}

// ----------------------------------------------------------------------------- the file

const HEADER = `// GENERATED FILE — DO NOT EDIT.
//
// Emitted by tools/gen-agent-types.ts from the zod schemas in packages/protocol/src/agent.ts.
// Regenerate with \`npm run gen:agent-types\`. tools/gen-agent-types.test.ts fails if this file is
// stale, so a renamed field on the TypeScript side becomes a Swift compile error here rather than a
// silent runtime mismatch across the stdio pipe.

import Foundation`

/**
 * Hand-written, not derived: the value side of the `log` event's metadata bag. It is deliberately
 * NOT a general JSON value — there is no `.object` or `.array` case, because the host drops the
 * agent's log fields anyway and a nested payload is where clipboard bytes would hide.
 */
const LOG_VALUE = `/// A single \`log\` event field value. Metadata only — never clipboard bytes.
enum AgentLogValue: Codable, Equatable, Sendable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case null

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Double.self) {
            self = .number(value)
        } else {
            self = .string(try container.decode(String.self))
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}`

function stringEnum(name: string, doc: string, values: readonly string[]): string {
  const cases = values.map((v) => `    case ${ident(camel(v))} = "${v}"`).join('\n')
  return `/// ${doc}\nenum ${name}: String, Codable, Equatable, Sendable, CaseIterable {\n${cases}\n}`
}

export function generateSwift(input: GenInput): string {
  const em: Emitter = { decls: new Map(), named: new Map(input.named) }

  for (const [method, params] of input.requests) emitStruct(`${pascal(method)}Params`, params, em)
  for (const [event, data] of input.events) emitStruct(`${pascal(event)}Data`, data, em)
  for (const [method, result] of input.results) {
    const name = `${pascal(method)}Result`
    const registered = em.named.get(result)
    if (registered !== undefined) {
      // e.g. `hello`'s result IS AgentCapabilities; alias it rather than emitting a twin struct.
      declare(em, name, `typealias ${name} = ${registered}`)
    } else {
      emitStruct(name, result, em)
    }
  }
  // Named schemas are reachable only if some field referenced them; force them all so the Swift
  // side always has `Rep`, `Hint`, `AgentCapabilities` and `AgentError` even if a field is dropped.
  for (const [schema, name] of input.named) {
    if (em.decls.has(name)) continue
    if (defOf(schema).type === 'enum') {
      const values = Object.values(defOf(schema).entries ?? {}).map(String)
      declare(em, name, stringEnum(name, `Values of the ${name} wire enum.`, values))
    } else {
      const shape = defOf(schema).shape
      if (shape === undefined) throw new GenError(`named schema '${name}' is neither an object nor an enum`)
      emitStruct(name, schema, em)
    }
  }

  const sections = [
    HEADER,
    `/// The wire major this agent speaks. Any other value must fail to parse.\nlet protocolVersion = ${input.wireMajor}`,
    stringEnum('AgentMethod', 'Every request the host may send.', input.requests.map(([m]) => m)),
    stringEnum('AgentEventName', 'Every event the agent may emit.', input.events.map(([e]) => e)),
    LOG_VALUE,
    ...[...em.decls.keys()].sort().map((k) => em.decls.get(k) ?? ''),
  ]
  return sections.join('\n\n') + '\n'
}

// ------------------------------------------------------------------------- entry point

export const GENERATED_PATH = join(
  dirname(dirname(fileURLToPath(import.meta.url))),
  'agents', 'macos', 'Sources', 'AgentProtocol.generated.swift',
)

/**
 * Node's ESM resolver has no extension search, but the contract's relative imports are
 * extensionless (`./result`) because `moduleResolution: bundler` resolves them for tsc, vite and
 * vitest. This hook adds `.ts` so `node tools/gen-agent-types.ts` can load the package source
 * directly, with no build step and no extra dependency. It is registered ONLY when this file is
 * the process entry point, so importing it from a test leaves Node's resolver untouched.
 */
function registerExtensionlessTsResolution(): void {
  registerHooks({
    resolve(specifier, context, nextResolve) {
      if (
        specifier.startsWith('.') &&
        !/\.[cm]?[jt]s$/.test(specifier) &&
        context.parentURL !== undefined
      ) {
        const candidate = new URL(`${specifier}.ts`, context.parentURL)
        if (existsSync(fileURLToPath(candidate))) return { url: candidate.href, shortCircuit: true }
      }
      return nextResolve(specifier, context)
    },
  })
}

const isEntryPoint =
  process.argv[1] !== undefined &&
  pathToFileURL(resolve(process.argv[1])).href === import.meta.url

if (isEntryPoint) {
  registerExtensionlessTsResolution()
  const protocol = (await import('@cairn/protocol')) as unknown as ProtocolSchemas
  const next = generateSwift(agentGenInput(protocol))
  const previous = existsSync(GENERATED_PATH) ? readFileSync(GENERATED_PATH, 'utf8') : ''
  if (previous === next) {
    process.stdout.write(`gen:agent-types — up to date (${GENERATED_PATH})\n`)
  } else {
    mkdirSync(dirname(GENERATED_PATH), { recursive: true })
    writeFileSync(GENERATED_PATH, next, { encoding: 'utf8' })
    process.stdout.write(`gen:agent-types — wrote ${next.length} bytes to ${GENERATED_PATH}\n`)
  }
}
